/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import model.Ingredient;
import model.Recipe;
import model.Recipe_Ingredient;
import model.Step;

/**
 *
 * @author nguye
 */
public class RecipeEditFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(RecipeEditFrame.class.getName());
    private final Recipe recipe;
    private final RecipeManagementFrame parentFrame;
    public RecipeEditFrame(RecipeManagementFrame parent, Recipe recipe) {
        this.parentFrame = parent;
        this.recipe = recipe;
        initComponents();
        txtID.setEditable(false);
        initializeTableModels();
        populateDetails();
    }
    private void populateDetails() {
        this.setTitle("Chỉnh sửa: " + recipe.getTitle());
        lblEdit.setText("Sửa công thức: " + recipe.getTitle());
        txtID.setText(String.valueOf(recipe.getRecipeID()));
        txtName.setText(recipe.getTitle());
        txtDesc.setText(recipe.getDescription());
        txtImagePath.setText(recipe.getImageURL());
        loadIngredientTable(recipe.getIngredients());
        loadStepTable(recipe.getSteps());
    }
    private void initializeTableModels() {
        DefaultTableModel ingredientModel = new DefaultTableModel(new Object[]{"ID Nguyên liệu", "Tên", "Số lượng", "Đơn vị", "Đường dẫn Ảnh"}, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return column >= 1 && column <= 3;
            }
        };
        tblIngredients.setModel(ingredientModel);
        DefaultTableModel stepModel = new DefaultTableModel(new Object[]{"STT", "Mô tả Bước", "Đường dẫn Ảnh"}, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return column == 1;
            }
        };
        tblSteps.setModel(stepModel);
    }
     
    private void loadIngredientTable(ArrayList<Recipe_Ingredient> ingredients) {
        DefaultTableModel model = (DefaultTableModel) tblIngredients.getModel();
        model.setRowCount(0);
        if (ingredients != null) {
            for (Recipe_Ingredient ri : ingredients) {
                Ingredient ing = ri.getIngredient();
                model.addRow(new Object[]{
                    ing.getIngredientID(),
                    ing.getName(),
                    ri.getQuantity(),
                    ri.getUnit(),
                    ing.getImageURL()
                });
            }
        }
    }
    
    private void loadStepTable(ArrayList<Step> steps) {
        DefaultTableModel model = (DefaultTableModel) tblSteps.getModel();
        model.setRowCount(0);
        if (steps != null) {
            for (Step step : steps) {
                model.addRow(new Object[]{
                    step.getStepNumber(),
                    step.getDescription(),
                    step.getImageURL()
                });
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        lblEdit = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        txtImagePath = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDesc = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblIngredients = new javax.swing.JTable();
        btnAddIngredient = new javax.swing.JButton();
        btnDelIngredient = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblSteps = new javax.swing.JTable();
        btnAddStep = new javax.swing.JButton();
        btnDelStep = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 700));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        lblEdit.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblEdit.setText("Sửa công thức");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 56, 0, 0);
        getContentPane().add(lblEdit, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(27, 44, 0, 0);
        getContentPane().add(txtID, gridBagConstraints);

        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 157;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(27, 6, 0, 0);
        getContentPane().add(txtName, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.ipadx = 334;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(27, 6, 0, 42);
        getContentPane().add(txtImagePath, gridBagConstraints);

        txtDesc.setColumns(20);
        txtDesc.setRows(5);
        jScrollPane1.setViewportView(txtDesc);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 13;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 692;
        gridBagConstraints.ipady = 114;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(6, 44, 0, 42);
        getContentPane().add(jScrollPane1, gridBagConstraints);

        tblIngredients.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Tên nguyên liệu", "Đường dẫn ảnh"
            }
        ));
        jScrollPane2.setViewportView(tblIngredients);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 13;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 692;
        gridBagConstraints.ipady = 116;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(6, 44, 0, 42);
        getContentPane().add(jScrollPane2, gridBagConstraints);

        btnAddIngredient.setText("Thêm nguyên liệu");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 36, 0, 0);
        getContentPane().add(btnAddIngredient, gridBagConstraints);

        btnDelIngredient.setText("Xóa nguyên liệu");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 58, 0, 0);
        getContentPane().add(btnDelIngredient, gridBagConstraints);

        tblSteps.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "STT", "Đường dẫn ảnh", "Mô tả bước"
            }
        ));
        jScrollPane3.setViewportView(tblSteps);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 13;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 692;
        gridBagConstraints.ipady = 316;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(6, 44, 0, 42);
        getContentPane().add(jScrollPane3, gridBagConstraints);

        btnAddStep.setText("Thêm bước");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 46, 0, 0);
        getContentPane().add(btnAddStep, gridBagConstraints);

        btnDelStep.setText("Xóa bước");
        btnDelStep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelStepActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 78, 0, 0);
        getContentPane().add(btnDelStep, gridBagConstraints);

        btnSave.setText("Lưu");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 16, 15, 0);
        getContentPane().add(btnSave, gridBagConstraints);

        btnCancel.setText("Hủy");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 15, 0);
        getContentPane().add(btnCancel, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void btnDelStepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelStepActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDelStepActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddIngredient;
    private javax.swing.JButton btnAddStep;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnDelIngredient;
    private javax.swing.JButton btnDelStep;
    private javax.swing.JButton btnSave;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblEdit;
    private javax.swing.JTable tblIngredients;
    private javax.swing.JTable tblSteps;
    private javax.swing.JTextArea txtDesc;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtImagePath;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables
}
